### ISSUE TITLE
Docker: apt-get update cache is not kept between installs

### ISSUE THREAD

**Issue by desimone** [ebonyclock/vizdoom_cig2017#4]
Ran into an issue while trying to run (and create) a few dockerfiles.

There are many instances where an `apt-get update` and an `apt-get install ...` are run on separate lines. This causes sync issues. For example, after the initial `apt-get install {system_updates}` there was a subsequent `apt-get install`...

```docker
Step 5/20 : RUN apt-get install -y python-dev python python-pip
 ---> Running in e214c2e0e6cd
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-dev
E: Unable to locate package python
E: Unable to locate package python-pip
```

Did some google'ing and found that [docker](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run) prefers update and install commands should always be chained with an `&&`. Therefore, many of the Dockerfile commands  should be

```docker
RUN apt-get update && apt-get install -y python-dev python python-pip
```

vs
```docker
RUN apt-get update
RUN apt-get install -y python-dev python python-pip
```

**Comment by mihahauke** [comment]
I have joined updates with installs when it wasn't that way already. I hope I haven't missed anything.
